"""TMRL configuration: load and expose settings from TmrlData/config/config.json.

Config file layout (config.json):
  __VERSION__     - Minimum compatible config version
  RUN_NAME        - Experiment name (used in paths and wandb)
  BUFFERS_MAXLEN  - Max samples per rollout worker buffer
  RW_MAX_SAMPLES_PER_EPISODE - Cap on steps per episode for workers
  CUDA_TRAINING   - Use GPU for trainer
  CUDA_INFERENCE - Use GPU for rollout workers
  VIRTUAL_GAMEPAD - Use gamepad (True) or keyboard (False)
  LOCALHOST_WORKER / LOCALHOST_TRAINER - Use 127.0.0.1 when same machine as server
  PUBLIC_IP_SERVER - Server IP for remote workers/trainers
  ENV             - Environment: RTGYM_INTERFACE, SEED, MAP_NAME, rewards,
                  failure params, image/window
  MODEL           - Training loop, memory size, CNN/RNN/MLP sizes, scheduler
  ALG             - Algorithm (SAC/TQC/REDQSAC), learning rates, gamma, etc.
  DEBUGGER        - Profiling, CRC debug, wandb debug
  WANDB_*         - Weights & Biases project, entity, API key
  PORT, LOCAL_PORT_*, PASSWORD, TLS_*, NB_WORKERS, BUFFER_SIZE, HEADER_SIZE - Networking

Secrets are loaded from .env in current working dir and TmrlData; environment variables
WANDB_API_KEY/WANDB_KEY and TMRL_PASSWORD override config for WANDB_KEY and PASSWORD.
Missing sections are filled from _DEFAULT_TMRL_CONFIG (backward compatibility).
"""

from __future__ import annotations

# Re-export all configuration components for backward compatibility
from tmrl.config.constants import (  # noqa: F401
    ACT_BUF_LEN,
    ACTOR_WEIGHT_DECAY,
    ALG_CONFIG,
    BACKUP_CLIP_RANGE,
    BATCH_SIZE,
    BINARY_BRAKE,
    BUFFER_SIZE,
    BUFFERS_MAXLEN,
    CHECKPOINT_COOLDOWN,
    CHECKPOINT_REWARD,
    CONSTANT_PENALTY,
    CRASH_COOLDOWN,
    CRASH_PENALTY,
    CRC_DEBUG,
    CRC_DEBUG_SAMPLES,
    CUDA_INFERENCE,
    CUDA_TRAINING,
    DEBUG_MODE,
    DEMO_MAX_BATCH_FRACTION,
    DEMO_MIN_BATCH_FRACTION,
    DEMO_SAMPLING_WEIGHT,
    DEMO_WEIGHT_DECAY_SAMPLES,
    DEMO_WEIGHT_DECAY_SLOWDOWN,
    END_OF_TRACK_REWARD,
    ENTROPY_COSINE_DECAY,
    ENTROPY_COSINE_T0,
    ENTROPY_COSINE_TMULT,
    ENTROPY_FLOOR,
    ENTROPY_SCHEDULE,
    ENVIRONMENT_STEPS_BEFORE_TRAINING,
    GAMMA,
    GRAD_CLIP_ACTOR,
    GRAD_CLIP_CRITIC,
    GRAYSCALE,
    HEADER_SIZE,
    HOSTNAME,
    IMG_HEIGHT,
    IMG_HIST_LEN,
    IMG_SCALE_CHECK_ENV,
    IMG_WIDTH,
    INIT_GAS_BIAS,
    LAP_COOLDOWN,
    LAP_REWARD,
    LINUX_X_OFFSET,
    LINUX_Y_OFFSET,
    LOCAL_PORT_SERVER,
    LOCAL_PORT_TRAINER,
    LOCAL_PORT_WORKER,
    LOCALHOST_TRAINER,
    LOCALHOST_WORKER,
    LRN_HIDDEN_SIZE,
    MAX_EPOCHS,
    MAX_NB_STEPS_BEFORE_FAILURE,
    MAX_NB_ZERO_REW_BEFORE_FAILURE,
    MAX_SPEED_KMH,
    MAX_TRAINING_STEPS_PER_ENVIRONMENT_STEP,
    MEMORY_SIZE,
    MIN_NB_STEPS_BEFORE_FAILURE,
    MIN_NB_ZERO_REW_BEFORE_FAILURE,
    MODEL_CONFIG,
    MODEL_HISTORY,
    N_STEPS,
    NB_OBS_FORWARD,
    NB_WORKERS,
    NOISY_LINEAR_ACTOR,
    NOISY_LINEAR_CRITIC,
    OBS_SPEED_SCALE,
    OBS_TRACK_SCALE,
    OBSERVATION_BOUNDS_CHECK,
    OSCILLATION_PERIOD,
    PASSWORD,
    PER_TD_ALPHA,
    PER_TD_ENABLED,
    PER_TD_EPS,
    PLAYER_RUNS_CONSUME_ON_READ,
    PLAYER_RUNS_DEMO_INJECTION_REPEAT,
    PLAYER_RUNS_MAX_FILES_PER_UPDATE,
    PLAYER_RUNS_ONLINE_INJECTION,
    PLAYER_RUNS_PER_ALPHA,
    PLAYER_RUNS_SOURCE_PATH,
    POINTS_DISTANCE,
    POINTS_NUMBER,
    POLYAK,
    PORT,
    PRAGMA_BEST,
    PRAGMA_BEST_TQC,
    PRAGMA_CUSTOM,
    PRAGMA_GAMEPAD,
    PRAGMA_LIDAR,
    PRAGMA_LIDAR_PROGRESS_IMAGES,
    PRAGMA_MBEST_TQC,
    PRAGMA_PROGRESS,
    PRAGMA_RNN,
    PRAGMA_TQC_GRAB,
    PRAGMA_TQC_GRAB_IMAGES,
    PRAGMA_TRACKMAP,
    PRAGMA_TRACKMAP_IMAGES,
    PRINT_BYTESIZES,
    PROFILE_TRAINER,
    PUBLIC_IP_SERVER,
    PYTORCH_PROFILER,
    QUANTILES_NUMBER,
    REWARD_CONFIG,
    # Additional aliases for backward compatibility
    RNN_HIDDEN_SIZE,
    ROUDS_PER_EPOCH,
    ROUNDS_PER_EPOCH,
    RTGYM_INTERFACE,
    RTGYM_VERSION,
    RUN_NAME,
    RW_MAX_SAMPLES_PER_EPISODE,
    RW_TEST_EPISODE_INTERVAL,
    RW_TEST_EPISODES_PER_EVAL,
    SCHEDULER_CONFIG,
    SDE_CLIP_MEAN,
    SDE_SAMPLE_FREQ,
    SECURITY,
    SEED,
    SLEEP_TIME_AT_RESET,
    SPEED_BONUS,
    SPEED_MEDIUM_THRESHOLD,
    SPEED_MIN_THRESHOLD,
    SYNCHRONIZE_CUDA,
    SYSTEM,
    TARGET_ENTROPY,
    TOP_QUANTILES_TO_DROP,
    TRACK_ENCODER,
    TRACK_POINTS_NUMBER,
    TRAINING_STEPS_PER_ROUND,
    UPDATE_BUFFER_INTERVAL,
    UPDATE_MODEL_INTERVAL,
    USE_BEST_INTERFACE,
    USE_BEST_TQC,
    USE_CUSTOM_BACKBONE,
    USE_EFFICIENTNET,
    USE_FROZEN_EFFNET,
    USE_IMAGES,
    USE_LIDAR_OBSERVATIONS,
    USE_LIDAR_PROGRESS,
    USE_LIDAR_PROGRESS_IMAGES,
    USE_MBEST_TQC,
    USE_RNN,
    USE_RNN_MODEL,
    USE_SDE,
    USE_TQC_GRAB,
    USE_TQC_GRAB_IMAGES,
    USE_TRACKMAP,
    USE_TRACKMAP_IMAGES,
    USE_VIRTUAL_GAMEPAD,
    WANDB_DEBUG,
    WANDB_DEBUG_REWARD,
    WANDB_ENTITY,
    WANDB_GRADIENTS,
    WANDB_KEY,
    WANDB_PROJECT,
    WANDB_RUN_ID,
    WANDB_WORKER,
    WEIGHT_CLIPPING_ENABLED,
    WEIGHT_CLIPPING_VALUE,
    WINDOW_HEIGHT,
    WINDOW_WIDTH,
)
from tmrl.config.defaults import _DEFAULT_TMRL_CONFIG, deep_merge_defaults
from tmrl.config.enums import AlgorithmName
from tmrl.config.loader import (
    CONFIG_COMPATIBILITY_ERROR_MESSAGE,
    CONFIG_FILE_PATH,
    CONFIG_VERSION,
    DEBUGGER,
    DEBUGGER_CONFIG,
    ENV_CONFIG,
    MINIMUM_CONFIG_VERSION,
    TMRL_CONFIG,
    TMRL_FOLDER,
    create_config,
)
from tmrl.config.models import AlgConfig, DebuggerConfig, EnvConfig, RewardConfig
from tmrl.config.paths import (
    CHECKPOINT_PATH,
    CHECKPOINTS_FOLDER,
    CONFIG_FOLDER,
    DATASET_FOLDER,
    DATASET_PATH,
    MAP_NAME,
    MODEL_PATH_SAVE_HISTORY,
    MODEL_PATH_TRAINER,
    MODEL_PATH_WORKER,
    PATH_DATA,
    PLAYER_RUNS_FOLDER,
    REWARD_FOLDER,
    REWARD_PATH,
    REWARDS_CHECKPOINT_PATH,
    TRACK_FOLDER,
    TRACK_PATH_LEFT,
    TRACK_PATH_RIGHT,
    WEIGHTS_FOLDER,
)

# Re-export paths module components
SERVER_IP_FOR_TRAINER = PUBLIC_IP_SERVER if not LOCALHOST_TRAINER else "127.0.0.1"
SERVER_IP_FOR_WORKER = PUBLIC_IP_SERVER if not LOCALHOST_WORKER else "127.0.0.1"

# Re-export algorithm constants
LR_ACTOR = ALG_CONFIG["LR_ACTOR"]
LR_CRITIC = ALG_CONFIG["LR_CRITIC"]
LR_ENTROPY = ALG_CONFIG["LR_ENTROPY"]
ALPHA = ALG_CONFIG["ALPHA"]
LEARN_ENTROPY_COEF = ALG_CONFIG["LEARN_ENTROPY_COEF"]

# Re-export model architecture constants
CNN_FILTERS = MODEL_CONFIG["CNN_FILTERS"]
CNN_OUTPUT_SIZE = MODEL_CONFIG["CNN_OUTPUT_SIZE"]
RNN_LENS = MODEL_CONFIG["RNN_LENS"]
RNN_SIZES = MODEL_CONFIG["RNN_SIZES"]
API_MLP_SIZES = MODEL_CONFIG["API_MLP_SIZES"]
API_LAYERNORM = MODEL_CONFIG["API_LAYERNORM"]
MLP_LAYERNORM = MODEL_CONFIG["MLP_LAYERNORM"]

# Re-export residual MLP constants
USE_RESIDUAL_MLP = MODEL_CONFIG.get("USE_RESIDUAL_MLP", False)
RESIDUAL_MLP_HIDDEN_DIM = MODEL_CONFIG.get("RESIDUAL_MLP_HIDDEN_DIM", 256)
RESIDUAL_MLP_NUM_BLOCKS = MODEL_CONFIG.get("RESIDUAL_MLP_NUM_BLOCKS", 6)
_RESIDUAL_MLP_NUM_BLOCKS_ACTOR = MODEL_CONFIG.get("RESIDUAL_MLP_NUM_BLOCKS_ACTOR", 0)
_RESIDUAL_MLP_NUM_BLOCKS_CRITIC = MODEL_CONFIG.get("RESIDUAL_MLP_NUM_BLOCKS_CRITIC", 0)
RESIDUAL_MLP_NUM_BLOCKS_ACTOR = (
    _RESIDUAL_MLP_NUM_BLOCKS_ACTOR
    if _RESIDUAL_MLP_NUM_BLOCKS_ACTOR > 0
    else RESIDUAL_MLP_NUM_BLOCKS
)
RESIDUAL_MLP_NUM_BLOCKS_CRITIC = (
    _RESIDUAL_MLP_NUM_BLOCKS_CRITIC
    if _RESIDUAL_MLP_NUM_BLOCKS_CRITIC > 0
    else RESIDUAL_MLP_NUM_BLOCKS
)

# Re-export Sophy/Track constants
USE_RESIDUAL_SOPHY = MODEL_CONFIG.get("USE_RESIDUAL_SOPHY", False)
USE_TRACK_CONV1D = MODEL_CONFIG.get("USE_TRACK_CONV1D", True)
USE_SIMBAV2 = MODEL_CONFIG.get("USE_SIMBAV2", False)
# TRACK_ENCODER already imported from constants
GNN_LAYERS = MODEL_CONFIG.get("GNN_LAYERS", 3)
GNN_HIDDEN = MODEL_CONFIG.get("GNN_HIDDEN", 64)

# Re-export EfficientNet constants
# USE_EFFICIENTNET and USE_FROZEN_EFFNET already imported from constants
FROZEN_EFFNET_EMBED_DIM = MODEL_CONFIG.get("FROZEN_EFFNET_EMBED_DIM", 256)
FROZEN_EFFNET_WIDTH_MULT = MODEL_CONFIG.get("FROZEN_EFFNET_WIDTH_MULT", 0.5)
FROZEN_EFFNET_VARIANT = MODEL_CONFIG.get("FROZEN_EFFNET_VARIANT", "xs")
FROZEN_EFFNET_USE_DW_STEM = MODEL_CONFIG.get("FROZEN_EFFNET_USE_DW_STEM", False)

# Re-export credential directory
CREDENTIALS_DIRECTORY = (
    TMRL_CONFIG["TLS_CREDENTIALS_DIRECTORY"]
    if TMRL_CONFIG.get("TLS_CREDENTIALS_DIRECTORY") != ""
    else None
)

# Lidar black threshold (constant)
LIDAR_BLACK_THRESHOLD = [55, 55, 55]

__all__ = [
    # Enums
    "AlgorithmName",
    # Models
    "RewardConfig",
    "EnvConfig",
    "DebuggerConfig",
    "AlgConfig",
    # Loader
    "TMRL_CONFIG",
    "ENV_CONFIG",
    "ALG_CONFIG",
    "DEBUGGER",
    "DEBUGGER_CONFIG",
    "CONFIG_FILE_PATH",
    "CONFIG_VERSION",
    "MINIMUM_CONFIG_VERSION",
    "CONFIG_COMPATIBILITY_ERROR_MESSAGE",
    "TMRL_FOLDER",
    "create_config",
    "deep_merge_defaults",
    "_DEFAULT_TMRL_CONFIG",
    # Paths
    "CHECKPOINTS_FOLDER",
    "DATASET_FOLDER",
    "REWARD_FOLDER",
    "TRACK_FOLDER",
    "WEIGHTS_FOLDER",
    "CONFIG_FOLDER",
    "PATH_DATA",
    "RUN_NAME",
    "BUFFERS_MAXLEN",
    "RW_MAX_SAMPLES_PER_EPISODE",
    "RW_TEST_EPISODE_INTERVAL",
    "RW_TEST_EPISODES_PER_EVAL",
    "CUDA_TRAINING",
    "CUDA_INFERENCE",
    "USE_VIRTUAL_GAMEPAD",
    "USE_RNN",
    "PRAGMA_RNN",
    "PRAGMA_GAMEPAD",
    "LOCALHOST_WORKER",
    "LOCALHOST_TRAINER",
    "PUBLIC_IP_SERVER",
    "SERVER_IP_FOR_WORKER",
    "SERVER_IP_FOR_TRAINER",
    "WANDB_RUN_ID",
    "WANDB_PROJECT",
    "WANDB_ENTITY",
    "WANDB_KEY",
    "WANDB_GRADIENTS",
    "WANDB_DEBUG_REWARD",
    "WANDB_WORKER",
    "PRINT_BYTESIZES",
    "PORT",
    "LOCAL_PORT_SERVER",
    "LOCAL_PORT_TRAINER",
    "LOCAL_PORT_WORKER",
    "PASSWORD",
    "SECURITY",
    "CREDENTIALS_DIRECTORY",
    "HOSTNAME",
    "NB_WORKERS",
    "BUFFER_SIZE",
    "HEADER_SIZE",
    "MODEL_CONFIG",
    "MODEL_HISTORY",
    "SCHEDULER_CONFIG",
    "NOISY_LINEAR_CRITIC",
    "NOISY_LINEAR_ACTOR",
    "CNN_FILTERS",
    "CNN_OUTPUT_SIZE",
    "RNN_LENS",
    "RNN_SIZES",
    "API_MLP_SIZES",
    "API_LAYERNORM",
    "MLP_LAYERNORM",
    "USE_RESIDUAL_MLP",
    "RESIDUAL_MLP_HIDDEN_DIM",
    "RESIDUAL_MLP_NUM_BLOCKS",
    "RESIDUAL_MLP_NUM_BLOCKS_ACTOR",
    "RESIDUAL_MLP_NUM_BLOCKS_CRITIC",
    "USE_RESIDUAL_SOPHY",
    "USE_TRACK_CONV1D",
    "USE_SIMBAV2",
    "TRACK_ENCODER",
    "GNN_LAYERS",
    "GNN_HIDDEN",
    "BINARY_BRAKE",
    "USE_RNN_MODEL",
    "RNN_HIDDEN_SIZE",
    "USE_EFFICIENTNET",
    "USE_FROZEN_EFFNET",
    "FROZEN_EFFNET_EMBED_DIM",
    "FROZEN_EFFNET_WIDTH_MULT",
    "FROZEN_EFFNET_VARIANT",
    "FROZEN_EFFNET_USE_DW_STEM",
    "RTGYM_INTERFACE",
    "USE_LIDAR_OBSERVATIONS",
    "USE_CUSTOM_BACKBONE",
    "USE_LIDAR_PROGRESS",
    "USE_LIDAR_PROGRESS_IMAGES",
    "USE_TRACKMAP",
    "USE_TRACKMAP_IMAGES",
    "USE_BEST_INTERFACE",
    "USE_BEST_TQC",
    "USE_MBEST_TQC",
    "USE_TQC_GRAB",
    "USE_TQC_GRAB_IMAGES",
    "PRAGMA_LIDAR",
    "PRAGMA_CUSTOM",
    "PRAGMA_PROGRESS",
    "PRAGMA_LIDAR_PROGRESS_IMAGES",
    "PRAGMA_TRACKMAP",
    "PRAGMA_TRACKMAP_IMAGES",
    "PRAGMA_BEST",
    "PRAGMA_BEST_TQC",
    "PRAGMA_MBEST_TQC",
    "PRAGMA_TQC_GRAB",
    "PRAGMA_TQC_GRAB_IMAGES",
    "SEED",
    "MAP_NAME",
    "MIN_NB_ZERO_REW_BEFORE_FAILURE",
    "MAX_NB_ZERO_REW_BEFORE_FAILURE",
    "MIN_NB_STEPS_BEFORE_FAILURE",
    "MAX_NB_STEPS_BEFORE_FAILURE",
    "OSCILLATION_PERIOD",
    "NB_OBS_FORWARD",
    "CRASH_PENALTY",
    "CRASH_COOLDOWN",
    "CONSTANT_PENALTY",
    "LAP_REWARD",
    "LAP_COOLDOWN",
    "CHECKPOINT_REWARD",
    "CHECKPOINT_COOLDOWN",
    "END_OF_TRACK_REWARD",
    "USE_IMAGES",
    "LIDAR_BLACK_THRESHOLD",
    "REWARD_CONFIG",
    "SLEEP_TIME_AT_RESET",
    "IMG_HIST_LEN",
    "ACT_BUF_LEN",
    "WINDOW_WIDTH",
    "WINDOW_HEIGHT",
    "GRAYSCALE",
    "IMG_WIDTH",
    "IMG_HEIGHT",
    "LINUX_X_OFFSET",
    "LINUX_Y_OFFSET",
    "IMG_SCALE_CHECK_ENV",
    "INIT_GAS_BIAS",
    "OBS_SPEED_SCALE",
    "OBS_TRACK_SCALE",
    "DEBUG_MODE",
    "CRC_DEBUG",
    "CRC_DEBUG_SAMPLES",
    "PROFILE_TRAINER",
    "SYNCHRONIZE_CUDA",
    "WANDB_DEBUG",
    "PYTORCH_PROFILER",
    "OBSERVATION_BOUNDS_CHECK",
    "PATH_DATA",
    "CHECKPOINT_PATH",
    "REWARDS_CHECKPOINT_PATH",
    "DATASET_PATH",
    "REWARD_PATH",
    "TRACK_PATH_LEFT",
    "TRACK_PATH_RIGHT",
    "TRACK_POINTS_NUMBER",
    "PLAYER_RUNS_FOLDER",
    "PLAYER_RUNS_ONLINE_INJECTION",
    "PLAYER_RUNS_SOURCE_PATH",
    "PLAYER_RUNS_CONSUME_ON_READ",
    "PLAYER_RUNS_MAX_FILES_PER_UPDATE",
    "PLAYER_RUNS_DEMO_INJECTION_REPEAT",
    "PLAYER_RUNS_PER_ALPHA",
    "DEMO_MAX_BATCH_FRACTION",
    "DEMO_MIN_BATCH_FRACTION",
    "DEMO_SAMPLING_WEIGHT",
    "DEMO_WEIGHT_DECAY_SAMPLES",
    "DEMO_WEIGHT_DECAY_SLOWDOWN",
    "MODEL_PATH_WORKER",
    "MODEL_PATH_SAVE_HISTORY",
    "MODEL_PATH_TRAINER",
    "QUANTILES_NUMBER",
    "N_STEPS",
    "WEIGHT_CLIPPING_ENABLED",
    "WEIGHT_CLIPPING_VALUE",
    "ACTOR_WEIGHT_DECAY",
    "CRITIC_WEIGHT_DECAY",
    "POINTS_NUMBER",
    "POINTS_DISTANCE",
    "SPEED_BONUS",
    "SPEED_MIN_THRESHOLD",
    "SPEED_MEDIUM_THRESHOLD",
    "MAX_SPEED_KMH",
    "ADAM_EPS",
    "GRAD_CLIP_ACTOR",
    "GRAD_CLIP_CRITIC",
    "BACKUP_CLIP_RANGE",
    "USE_SDE",
    "LOG_STD_INIT",
    "SDE_CLIP_MEAN",
    "SDE_SAMPLE_FREQ",
    "ENTROPY_FLOOR",
    "ENTROPY_SCHEDULE",
    "ENTROPY_COSINE_T0",
    "ENTROPY_COSINE_TMULT",
    "ENTROPY_COSINE_DECAY",
    "PER_TD_ENABLED",
    "PER_TD_ALPHA",
    "PER_TD_EPS",
    "LR_ACTOR",
    "LR_CRITIC",
    "LR_ENTROPY",
    "ALPHA",
    "LEARN_ENTROPY_COEF",
    "GAMMA",
    "POLYAK",
    "TARGET_ENTROPY",
    "TOP_QUANTILES_TO_DROP",
    "TRAINING_STEPS_PER_ROUND",
    "MAX_TRAINING_STEPS_PER_ENVIRONMENT_STEP",
    "ENVIRONMENT_STEPS_BEFORE_TRAINING",
    "UPDATE_MODEL_INTERVAL",
    "UPDATE_BUFFER_INTERVAL",
    "SAVE_MODEL_EVERY",
    "MEMORY_SIZE",
    "BATCH_SIZE",
    "MAX_EPOCHS",
    "ROUNDS_PER_EPOCH",
    "ROUDS_PER_EPOCH",
    "SYSTEM",
    "RTGYM_VERSION",
]
