"""Derived configuration constants from validated MainConfig (Hydra + optional config.json)."""

from __future__ import annotations

import os
import pickle

from loguru import logger

from tmrl.config.loader import ENV_CONFIG, MAIN_CONFIG, TMRL_CONFIG
from tmrl.config.paths import PLAYER_RUNS_FOLDER, REWARD_PATH
from tmrl.config.spacing_lookahead import (
    points_number_from_spacing_config,
    polyline_arc_length_m,
)

M = MAIN_CONFIG

# =============================================================================
# Run Configuration
# =============================================================================

RUN_NAME = M.RUN_NAME
BUFFERS_MAXLEN = M.BUFFERS_MAXLEN
RW_MAX_SAMPLES_PER_EPISODE = M.RW_MAX_SAMPLES_PER_EPISODE
RW_TEST_EPISODE_INTERVAL = M.RW_TEST_EPISODE_INTERVAL
RW_TEST_EPISODES_PER_EVAL = M.RW_TEST_EPISODES_PER_EVAL

# =============================================================================
# Hardware Configuration
# =============================================================================

CUDA_TRAINING = M.CUDA_TRAINING
CUDA_INFERENCE = M.CUDA_INFERENCE
USE_VIRTUAL_GAMEPAD = M.VIRTUAL_GAMEPAD
USE_RNN = False

PRAGMA_RNN = USE_RNN
PRAGMA_GAMEPAD = USE_VIRTUAL_GAMEPAD

# =============================================================================
# Network Configuration
# =============================================================================

LOCALHOST_WORKER = M.LOCALHOST_WORKER
LOCALHOST_TRAINER = M.LOCALHOST_TRAINER
PUBLIC_IP_SERVER = M.PUBLIC_IP_SERVER
SERVER_IP_FOR_WORKER = PUBLIC_IP_SERVER if not LOCALHOST_WORKER else "127.0.0.1"
SERVER_IP_FOR_TRAINER = PUBLIC_IP_SERVER if not LOCALHOST_TRAINER else "127.0.0.1"

PORT = M.PORT
LOCAL_PORT_SERVER = M.LOCAL_PORT_SERVER
LOCAL_PORT_TRAINER = M.LOCAL_PORT_TRAINER
LOCAL_PORT_WORKER = M.LOCAL_PORT_WORKER
PASSWORD = M.PASSWORD
SECURITY = "TLS" if M.TLS else None
CREDENTIALS_DIRECTORY = M.TLS_CREDENTIALS_DIRECTORY if M.TLS_CREDENTIALS_DIRECTORY != "" else None
HOSTNAME = M.TLS_HOSTNAME
NB_WORKERS = None if M.NB_WORKERS < 0 else M.NB_WORKERS
BUFFER_SIZE = M.BUFFER_SIZE
HEADER_SIZE = M.HEADER_SIZE
PRINT_BYTESIZES = True

# =============================================================================
# Weights & Biases Configuration
# =============================================================================

WANDB_RUN_ID = RUN_NAME
WANDB_PROJECT = M.WANDB_PROJECT
WANDB_ENTITY = M.WANDB_ENTITY
WANDB_KEY = M.WANDB_KEY
WANDB_GRADIENTS = M.WANDB_GRADIENTS
WANDB_DEBUG_REWARD = M.WANDB_DEBUG_REWARD
WANDB_WORKER = M.WANDB_WORKER


def ensure_wandb_api_key() -> None:
    """Set WANDB_API_KEY in os.environ if not already present."""
    if "WANDB_API_KEY" not in os.environ and WANDB_KEY:
        os.environ["WANDB_API_KEY"] = WANDB_KEY


# =============================================================================
# Model Architecture Configuration
# =============================================================================

MODEL_CONFIG = TMRL_CONFIG["MODEL"]
MODEL_HISTORY = M.MODEL.SAVE_MODEL_EVERY
BEST_CHECKPOINT_CRITERION = M.MODEL.BEST_CHECKPOINT_CRITERION
BEST_CHECKPOINT_LAP_TIME = M.MODEL.BEST_CHECKPOINT_LAP_TIME
BEST_CHECKPOINT_MIN_FINISHES = M.MODEL.BEST_CHECKPOINT_MIN_FINISHES
COMPETITION_EVAL_CRASH_PENALTY_S = float(M.MODEL.COMPETITION_EVAL_CRASH_PENALTY_S)
COMPETITION_EVAL_MAX_CRASHES = int(M.MODEL.COMPETITION_EVAL_MAX_CRASHES)

MAX_EPOCHS = M.MODEL.MAX_EPOCHS
ROUNDS_PER_EPOCH = M.MODEL.ROUNDS_PER_EPOCH
TRAINING_STEPS_PER_ROUND = M.MODEL.TRAINING_STEPS_PER_ROUND
MAX_TRAINING_STEPS_PER_ENVIRONMENT_STEP = M.MODEL.MAX_TRAINING_STEPS_PER_ENVIRONMENT_STEP
ENVIRONMENT_STEPS_BEFORE_TRAINING = M.MODEL.ENVIRONMENT_STEPS_BEFORE_TRAINING
UPDATE_MODEL_INTERVAL = M.MODEL.UPDATE_MODEL_INTERVAL
UPDATE_BUFFER_INTERVAL = M.MODEL.UPDATE_BUFFER_INTERVAL

MEMORY_SIZE = M.MODEL.MEMORY_SIZE
BATCH_SIZE = M.MODEL.BATCH_SIZE
BATCHES_PER_STEP = M.MODEL.BATCHES_PER_STEP

SCHEDULER_CONFIG = TMRL_CONFIG["MODEL"]["SCHEDULER"]

CNN_FILTERS = M.MODEL.CNN_FILTERS
CNN_OUTPUT_SIZE = M.MODEL.CNN_OUTPUT_SIZE

RNN_LENS = M.MODEL.RNN_LENS
RNN_SIZES = M.MODEL.RNN_SIZES

API_MLP_SIZES = M.MODEL.API_MLP_SIZES
API_LAYERNORM = M.MODEL.API_LAYERNORM
MLP_LAYERNORM = M.MODEL.MLP_LAYERNORM

NOISY_LINEAR_CRITIC = M.MODEL.NOISY_LINEAR_CRITIC
NOISY_LINEAR_ACTOR = M.MODEL.NOISY_LINEAR_ACTOR
OUTPUT_DROPOUT = M.MODEL.OUTPUT_DROPOUT
RNN_DROPOUT = M.MODEL.RNN_DROPOUT

USE_RESIDUAL_MLP = M.MODEL.USE_RESIDUAL_MLP
RESIDUAL_MLP_HIDDEN_DIM = M.MODEL.RESIDUAL_MLP_HIDDEN_DIM
RESIDUAL_MLP_NUM_BLOCKS = M.MODEL.RESIDUAL_MLP_NUM_BLOCKS
_RESIDUAL_MLP_NUM_BLOCKS_ACTOR = M.MODEL.RESIDUAL_MLP_NUM_BLOCKS_ACTOR
_RESIDUAL_MLP_NUM_BLOCKS_CRITIC = M.MODEL.RESIDUAL_MLP_NUM_BLOCKS_CRITIC
RESIDUAL_MLP_NUM_BLOCKS_ACTOR = (
    _RESIDUAL_MLP_NUM_BLOCKS_ACTOR
    if _RESIDUAL_MLP_NUM_BLOCKS_ACTOR > 0
    else RESIDUAL_MLP_NUM_BLOCKS
)
RESIDUAL_MLP_NUM_BLOCKS_CRITIC = (
    _RESIDUAL_MLP_NUM_BLOCKS_CRITIC
    if _RESIDUAL_MLP_NUM_BLOCKS_CRITIC > 0
    else RESIDUAL_MLP_NUM_BLOCKS
)

USE_RESIDUAL_SOPHY = M.MODEL.USE_RESIDUAL_SOPHY
USE_TRACK_CONV1D = M.MODEL.USE_TRACK_CONV1D
USE_SIMBAV2 = M.MODEL.USE_SIMBAV2
TRACK_ENCODER = M.MODEL.TRACK_ENCODER
GNN_LAYERS = M.MODEL.GNN_LAYERS
GNN_HIDDEN = M.MODEL.GNN_HIDDEN

USE_RNN_MODEL = M.MODEL.USE_RNN
_RNN_HIDDEN_SIZE = M.MODEL.RNN_HIDDEN_SIZE
RNN_HIDDEN_SIZE = _RNN_HIDDEN_SIZE if _RNN_HIDDEN_SIZE > 0 else RESIDUAL_MLP_HIDDEN_DIM

USE_EFFICIENTNET = M.MODEL.USE_EFFICIENTNET
USE_FROZEN_EFFNET = M.MODEL.USE_FROZEN_EFFNET
FROZEN_EFFNET_EMBED_DIM = M.MODEL.FROZEN_EFFNET_EMBED_DIM
FROZEN_EFFNET_WIDTH_MULT = M.MODEL.FROZEN_EFFNET_WIDTH_MULT
FROZEN_EFFNET_VARIANT = M.MODEL.FROZEN_EFFNET_VARIANT
FROZEN_EFFNET_USE_DW_STEM = M.MODEL.FROZEN_EFFNET_USE_DW_STEM

BINARY_BRAKE = M.MODEL.BINARY_BRAKE

# =============================================================================
# Environment Configuration
# =============================================================================

RTGYM_INTERFACE = str(M.ENV.RTGYM_INTERFACE).upper()

USE_LIDAR_OBSERVATIONS = RTGYM_INTERFACE.endswith("LIDAR")
USE_CUSTOM_BACKBONE = RTGYM_INTERFACE.endswith("MOBILEV3") or RTGYM_INTERFACE.endswith("CUSTOM")
USE_LIDAR_PROGRESS = RTGYM_INTERFACE.endswith("LIDARPROGRESS")
USE_LIDAR_PROGRESS_IMAGES = "LIDARPROGRESSIMAGES" in RTGYM_INTERFACE
USE_TRACKMAP = RTGYM_INTERFACE.endswith("TRACKMAP")
USE_TRACKMAP_IMAGES = "TRACKMAPIMAGES" in RTGYM_INTERFACE
USE_BEST_INTERFACE = RTGYM_INTERFACE.endswith("BEST")
USE_BEST_TQC = RTGYM_INTERFACE.endswith("BEST_TQC")
USE_MBEST_TQC = RTGYM_INTERFACE.endswith("MTQC")
USE_TQC_GRAB = "TQCGRAB" in RTGYM_INTERFACE
USE_TQC_GRAB_IMAGES = "TQCGRAB_IMAGES" in RTGYM_INTERFACE

PRAGMA_LIDAR = USE_LIDAR_OBSERVATIONS
PRAGMA_CUSTOM = USE_CUSTOM_BACKBONE
PRAGMA_PROGRESS = USE_LIDAR_PROGRESS
PRAGMA_LIDAR_PROGRESS_IMAGES = USE_LIDAR_PROGRESS_IMAGES
PRAGMA_TRACKMAP = USE_TRACKMAP
PRAGMA_TRACKMAP_IMAGES = USE_TRACKMAP_IMAGES
PRAGMA_BEST = USE_BEST_INTERFACE
PRAGMA_BEST_TQC = USE_BEST_TQC
PRAGMA_MBEST_TQC = USE_MBEST_TQC
PRAGMA_TQC_GRAB = USE_TQC_GRAB
PRAGMA_TQC_GRAB_IMAGES = USE_TQC_GRAB_IMAGES

if USE_LIDAR_PROGRESS or USE_TRACKMAP or USE_LIDAR_PROGRESS_IMAGES or USE_TRACKMAP_IMAGES:
    USE_LIDAR_OBSERVATIONS = True
    PRAGMA_LIDAR = True

SEED = M.ENV.SEED
MIN_NB_ZERO_REW_BEFORE_FAILURE = M.ENV.MIN_NB_ZERO_REW_BEFORE_FAILURE
MAX_NB_ZERO_REW_BEFORE_FAILURE = M.ENV.MAX_NB_ZERO_REW_BEFORE_FAILURE
MIN_NB_STEPS_BEFORE_FAILURE = M.ENV.MIN_NB_STEPS_BEFORE_FAILURE
MAX_NB_STEPS_BEFORE_FAILURE = MIN_NB_STEPS_BEFORE_FAILURE
OSCILLATION_PERIOD = M.ENV.OSCILLATION_PERIOD
NB_OBS_FORWARD = M.ENV.NB_OBS_FORWARD
CRASH_PENALTY = M.ENV.CRASH_PENALTY
CRASH_COOLDOWN = M.ENV.CRASH_COOLDOWN
CONSTANT_PENALTY = M.ENV.CONSTANT_PENALTY
LAP_REWARD = M.ENV.LAP_REWARD
LAP_COOLDOWN = M.ENV.LAP_COOLDOWN
CHECKPOINT_REWARD = M.ENV.CHECKPOINT_REWARD
CHECKPOINT_COOLDOWN = 0
END_OF_TRACK_REWARD = M.ENV.END_OF_TRACK_REWARD
USE_IMAGES = M.ENV.USE_IMAGES
SLEEP_TIME_AT_RESET = M.ENV.SLEEP_TIME_AT_RESET
IMG_HIST_LEN = M.ENV.IMG_HIST_LEN
ACT_BUF_LEN = M.ENV.RTGYM_CONFIG.act_buf_len
WINDOW_WIDTH = M.ENV.WINDOW_WIDTH
WINDOW_HEIGHT = M.ENV.WINDOW_HEIGHT
GRAYSCALE = M.ENV.IMG_GRAYSCALE
IMG_WIDTH = M.ENV.IMG_WIDTH
IMG_HEIGHT = M.ENV.IMG_HEIGHT
LINUX_X_OFFSET = M.ENV.LINUX_X_OFFSET
LINUX_Y_OFFSET = M.ENV.LINUX_Y_OFFSET
IMG_SCALE_CHECK_ENV = M.ENV.IMG_SCALE_CHECK_ENV
INIT_GAS_BIAS = M.ENV.INIT_GAS_BIAS
OBS_SPEED_SCALE = float(M.ENV.OBS_SPEED_SCALE)
OBS_TRACK_SCALE = float(M.ENV.OBS_TRACK_SCALE)

LIDAR_BLACK_THRESHOLD = [55, 55, 55]

REWARD_CONFIG = M.ENV.REWARD_CONFIG.model_dump()
MAX_SPEED_KMH = float(REWARD_CONFIG.get("MAX_SPEED_KMH", 300.0))

TRACK_POINTS_NUMBER = None
_rc = M.ENV.REWARD_CONFIG
_track_pct = float(_rc.TRACK_LOOK_AHEAD_PCT)
_track_spacing = float(_rc.TRACK_POINT_SPACING_M)
if _track_pct > 0 and _track_spacing > 0 and os.path.exists(REWARD_PATH):
    try:
        with open(REWARD_PATH, "rb") as _f:
            _traj = pickle.load(_f)
        _L = polyline_arc_length_m(_traj)
        if _L is not None:
            TRACK_POINTS_NUMBER = points_number_from_spacing_config(_L, _track_pct, _track_spacing)
            if TRACK_POINTS_NUMBER is not None:
                logger.info(
                    "Track look-ahead: TRACK_LOOK_AHEAD_PCT={:.2f}%, "
                    "TRACK_POINT_SPACING_M={:.2f} m, "
                    "trajectory length={:.1f} m -> POINTS_NUMBER={}",
                    _track_pct,
                    _track_spacing,
                    _L,
                    TRACK_POINTS_NUMBER,
                )
    except (FileNotFoundError, pickle.UnpicklingError, ValueError, OSError) as e:
        logger.warning(f"Failed to load reward trajectory for POINTS_NUMBER calculation: {e}")
elif _track_pct > 0 and _track_spacing > 0:
    logger.warning(
        f"TRACK_LOOK_AHEAD_PCT={_track_pct} is set but reward file {REWARD_PATH} is missing! "
        f"POINTS_NUMBER will fallback to default NUMBER_OF_POINTS. "
        "This will cause shape mismatches if other processes (e.g. Worker) have the file."
    )

# =============================================================================
# Algorithm Configuration
# =============================================================================

ALG_CONFIG = TMRL_CONFIG["ALG"]

QUANTILES_NUMBER = M.ALG.QUANTILES_NUMBER

GAMMA = M.ALG.GAMMA
POLYAK = M.ALG.POLYAK
TARGET_ENTROPY = M.ALG.TARGET_ENTROPY
TOP_QUANTILES_TO_DROP = M.ALG.TOP_QUANTILES_TO_DROP
N_STEPS = 1 if M.ALG.N_STEPS <= 0 else M.ALG.N_STEPS

WEIGHT_CLIPPING_ENABLED = M.ALG.CLIPPING_WEIGHTS
WEIGHT_CLIPPING_VALUE = 1.0 if not WEIGHT_CLIPPING_ENABLED else M.ALG.CLIP_WEIGHTS_VALUE

ACTOR_WEIGHT_DECAY = M.ALG.ACTOR_WEIGHT_DECAY
CRITIC_WEIGHT_DECAY = M.ALG.CRITIC_WEIGHT_DECAY

POINTS_NUMBER = (
    TRACK_POINTS_NUMBER if TRACK_POINTS_NUMBER is not None else M.ALG.NUMBER_OF_POINTS
)
POINTS_DISTANCE = M.ALG.POINTS_DISTANCE

SPEED_BONUS = M.ALG.SPEED_BONUS
SPEED_MIN_THRESHOLD = M.ALG.SPEED_MIN_THRESHOLD
SPEED_MEDIUM_THRESHOLD = M.ALG.SPEED_MEDIUM_THRESHOLD

ADAM_EPS = M.ALG.ADAM_EPS
GRAD_CLIP_ACTOR = float(M.ALG.GRAD_CLIP_ACTOR)
GRAD_CLIP_CRITIC = float(M.ALG.GRAD_CLIP_CRITIC)
BACKUP_CLIP_RANGE = float(M.ALG.BACKUP_CLIP_RANGE)

USE_SDE = bool(M.ALG.USE_SDE)
LOG_STD_INIT = float(M.ALG.LOG_STD_INIT)
SDE_CLIP_MEAN = float(M.ALG.SDE_CLIP_MEAN)
SDE_SAMPLE_FREQ = int(M.ALG.SDE_SAMPLE_FREQ)

ENTROPY_FLOOR = float(M.ALG.ENTROPY_FLOOR)
ENTROPY_SCHEDULE = str(M.ALG.ENTROPY_SCHEDULE)
ENTROPY_COSINE_T0 = int(M.ALG.ENTROPY_COSINE_T0)
ENTROPY_COSINE_TMULT = float(M.ALG.ENTROPY_COSINE_TMULT)
ENTROPY_COSINE_DECAY = float(M.ALG.ENTROPY_COSINE_DECAY)

PER_TD_ENABLED = bool(M.ALG.PER_TD_ENABLED)
PER_TD_ALPHA = float(M.ALG.PER_TD_ALPHA)
PER_TD_EPS = float(M.ALG.PER_TD_EPS)

# =============================================================================
# Debug Configuration
# =============================================================================

DEBUG_MODE = M.DEBUGGER.DEBUG_MODE
CRC_DEBUG = M.DEBUGGER.CRC_DEBUG
CRC_DEBUG_SAMPLES = M.DEBUGGER.CRC_DEBUG_SAMPLES
PROFILE_TRAINER = M.DEBUGGER.PROFILE_TRAINER
SYNCHRONIZE_CUDA = PROFILE_TRAINER
WANDB_DEBUG = M.DEBUGGER.WANDB_DEBUG
PYTORCH_PROFILER = M.DEBUGGER.PYTORCH_PROFILER
OBSERVATION_BOUNDS_CHECK = M.DEBUGGER.OBSERVATION_BOUNDS_CHECK

# =============================================================================
# Player Runs Configuration
# =============================================================================

_pr = M.PLAYER_RUNS
PLAYER_RUNS_ONLINE_INJECTION = _pr.ONLINE_INJECTION
PLAYER_RUNS_SOURCE_PATH = _pr.SOURCE_PATH if _pr.SOURCE_PATH else str(PLAYER_RUNS_FOLDER)
PLAYER_RUNS_CONSUME_ON_READ = _pr.CONSUME_ON_READ
PLAYER_RUNS_MAX_FILES_PER_UPDATE = _pr.MAX_FILES_PER_UPDATE
PLAYER_RUNS_DEMO_INJECTION_REPEAT = max(1, _pr.DEMO_INJECTION_REPEAT)
PLAYER_RUNS_PER_ALPHA = max(0.0, float(_pr.PER_ALPHA))
DEMO_MAX_BATCH_FRACTION = max(0.0, min(1.0, float(_pr.DEMO_MAX_BATCH_FRACTION)))
DEMO_MIN_BATCH_FRACTION = max(0.0, min(1.0, float(_pr.DEMO_MIN_BATCH_FRACTION)))
DEMO_SAMPLING_WEIGHT = max(0.0, float(_pr.DEMO_SAMPLING_WEIGHT))
DEMO_WEIGHT_DECAY_SAMPLES = max(0, int(_pr.DEMO_WEIGHT_DECAY_SAMPLES))
DEMO_WEIGHT_DECAY_SLOWDOWN = max(0.0, float(_pr.DEMO_WEIGHT_DECAY_SLOWDOWN))
