# @package _global_
defaults:
  - default
  - _self_

algorithm:
  _target_: tmrl.custom.custom_algorithms.redq_sac.REDQSACAgent
  name: REDQSAC
  learn_entropy_coef: true
  redq_n: 10
  redq_m: 2
  redq_q_updates_per_policy_update: 20
  mixed_precision: true
  mixed_precision_dtype: bfloat16
