"""Files generated by ``trackmaniarl init`` for a local extension project."""

from __future__ import annotations

from importlib.resources import files
from importlib.resources.abc import Traversable
from pathlib import Path

from trackmaniarl.project.scaffold_run_templates import _config, _trackmania_config
from trackmaniarl.project.scaffold_templates import (
    COMPONENTS,
    _project_readme,
    _pyproject,
    _uv_options,
)


def create_project(directory: str | Path, package: str, *, template: str = "starter") -> Path:
    """Create an installable, editable project without overwriting user files."""

    target, package_dir = _create_directories(directory, package, template)
    _write_project_metadata(target, package, template)
    if template == "trackmania":
        _write_trackmania_assets(target)
        _copy_openplanet_assets(target)
    _write_package(target, package_dir, package)
    return target


def _create_directories(directory: str | Path, package: str, template: str) -> tuple[Path, Path]:
    target = Path(directory)
    if target.exists() and any(target.iterdir()):
        raise FileExistsError(f"Refusing to overwrite non-empty directory {target}")
    if template not in {"starter", "trackmania"}:
        raise ValueError("template must be 'starter' or 'trackmania'")
    package_dir = target / "src" / package
    package_dir.mkdir(parents=True, exist_ok=True)
    return target, package_dir


def _write_project_metadata(target: Path, package: str, template: str) -> None:
    (target / "pyproject.toml").write_text(
        _generated_pyproject(package, template), encoding="utf-8"
    )
    (target / ".gitignore").write_text(
        ".env\n.venv/\nartifacts/\n__pycache__/\n.pytest_cache/\n.ruff_cache/\n"
        ".mypy_cache/\n*.egg-info/\ndist/\n",
        encoding="utf-8",
    )
    (target / ".env-example").write_text(
        "TRACKMANIARL_DISTRIBUTED_TOKEN=\n",
        encoding="utf-8",
    )
    (target / "README.md").write_text(_project_readme(template), encoding="utf-8")
    config = _config(package) if template == "starter" else _trackmania_config()
    (target / "run.yaml").write_text(config, encoding="utf-8")


def _generated_pyproject(package: str, template: str) -> str:
    extras = "[trackmania,distributed]" if template == "trackmania" else "[distributed]"
    project = _pyproject(
        package.replace("_", "-"),
        trackmaniarl_extras=extras,
        template=template,
    )
    return project + _uv_options(template)


def _write_trackmania_assets(target: Path) -> None:
    import numpy as np

    assets = target / "assets"
    assets.mkdir()
    (target / "maps").mkdir()
    boundary = np.asarray([[0, 0, -5], [5, 0, -5], [10, 0, -5]], dtype=np.float32)
    np.savez_compressed(
        assets / "trackmaniarl-test.geometry.npz",
        version=np.asarray("1"),
        map_uid=np.asarray("REPLACE_WITH_TEST_3_UID"),
        map_sha256=np.asarray(""),
        left=boundary,
        center=boundary + np.asarray([0, 0, 5], dtype=np.float32),
        right=boundary + np.asarray([0, 0, 10], dtype=np.float32),
        spacing_m=np.asarray(5.0, dtype=np.float32),
        recorded_count=np.asarray(len(boundary), dtype=np.int32),
    )


def _copy_openplanet_assets(target: Path) -> None:
    plugin_dir = target / "openplanet"
    plugin_dir.mkdir()
    resources = files("trackmaniarl.project").joinpath("openplanet")
    _copy_resource(
        resources.joinpath("TrackmaniaRL_Connect.as"),
        plugin_dir / "SAC_GetData-2.4.0-reference.as",
    )
    _copy_resource(resources.joinpath("info.toml"), plugin_dir / "info.reference.toml")
    _copy_resource(resources.joinpath("README.md"), plugin_dir / "README.md")


def _copy_resource(resource: Traversable, destination: Path) -> None:
    destination.write_text(resource.read_text(encoding="utf-8"), encoding="utf-8")


def _write_package(target: Path, package_dir: Path, package: str) -> None:
    (package_dir / "__init__.py").write_text("", encoding="utf-8")
    (package_dir / "components.py").write_text(COMPONENTS, encoding="utf-8")
    tests_dir = target / "tests"
    tests_dir.mkdir()
    (tests_dir / "test_components.py").write_text(
        f"from {package}.components import StarterMlpLearner\n\n\n"
        "def test_policy_is_constructible() -> None:\n"
        "    assert StarterMlpLearner().policy() is not None\n",
        encoding="utf-8",
    )
