# @package _global_
# Base interface parameters shared across all interface presets.
interface:
  name: lidar
  _target_: tmrl.custom.interfaces.boundary.TM2020InterfaceBoundary
  img_hist_len: 1
  gamepad: true
  grayscale: true
  resize_to: [64, 64]
  finish_reward: 1.0
  constant_penalty: 0.0
  crash_penalty: 2.0
  reward_check_forward: 500
  reward_check_backward: 10
  reward_max_stray: 50.0
  sleep_time_at_reset: 1.5
  window_width: 640
  window_height: 480
  discrete_n_steer_bins: 0
  points_number: 5
  checkpoint_reward: 0.0
  lap_reward: 0.0
  track_local_frame: false
  obs_speed_scale: 1.0
  obs_track_scale: 1.0
  min_steps_end_of_track: 50
  min_episode_length_guaranteed: 100
