# @package _global_
defaults:
  - default
  - _self_

interface:
  name: tqc
  _target_: tmrl.custom.interfaces.TM2020InterfaceTQC.TM2020InterfaceTQC
  img_hist_len: 1
  gamepad: false
  grayscale: false
  resize_to: [128, 64]
  constant_penalty: 0.05
