[meta]
name = "TrackmaniaRL Connect"
author = "Palamabron / AITrackmania"
category = "Trackmania Reinforcement Learning"
version = "2.4.0"
siteid = 421

[script]
dependencies = ["VehicleState", "PlayerState"]
