# @package _global_
# Process communication (tlspyo): ports, buffers, timeouts.
distributed:
  server_port: 55555
  local_port_server: 55556
  local_port_trainer: 55557
  local_port_worker: 55558
  buffer_size: 536870912
  header_size: 12
  socket_timeout_connect_trainer: 300.0
  socket_timeout_accept_trainer: 300.0
  socket_timeout_connect_rollout: 300.0
  socket_timeout_accept_rollout: 300.0
  socket_timeout_communicate: 30.0
  select_timeout_outbound: 30.0
  ack_timeout_worker_to_server: 300.0
  ack_timeout_trainer_to_server: 300.0
  ack_timeout_server_to_worker: 300.0
  ack_timeout_server_to_trainer: 7200.0
  recv_timeout_trainer_from_server: 7200.0
  recv_timeout_worker_from_server: 600.0
  wait_before_reconnection: 10.0
  loop_sleep_time: 1.0
  password: change_me
  use_tls: false
  tls_hostname: default
  tls_credentials_directory: ""
  public_ip_server: "0.0.0.0"
  localhost_worker: true
  localhost_trainer: true
  num_workers: -1
