"""Files generated by ``tmrl init`` for a local extension project."""

from __future__ import annotations

from importlib.resources import files
from pathlib import Path


def _tmrl_requirement() -> str:
    """Use this checkout while developing before the next package release exists."""

    source_root = Path(__file__).resolve().parents[2]
    if (source_root / "pyproject.toml").is_file():
        return f"tmrl @ {source_root.as_uri()}"
    return "tmrl>=1.0"


def _pyproject(name: str) -> str:
    return (
        '[build-system]\nrequires = ["setuptools>=65"]\n'
        'build-backend = "setuptools.build_meta"\n\n'
        '[project]\nname = "' + name + '"\nversion = "0.1.0"\n'
        'requires-python = ">=3.12"\ndependencies = ["'
        + _tmrl_requirement()
        + '", "torch>=2.4"]\n\n'
        '[tool.setuptools.packages.find]\nwhere = ["src"]\n'
    )


def _config(package: str) -> str:
    return f"""api_version: "1.1"
run_id: starter
seed: 0
artifacts_dir: artifacts
components:
  learner: {{class_path: {package}.components:StarterMlpLearner}}
  environment: {{class_path: {package}.components:StarterEnvironmentFactory}}
  replay_store: {{class_path: tmrl.core.replay:InMemoryReplayStore, kwargs: {{capacity: 10000}}}}
  sampler: {{class_path: tmrl.core.replay:UniformSampler, kwargs: {{seed: 0}}}}
  feature_pipeline: {{class_path: {package}.components:StarterFeaturePipeline}}
  logger: {{class_path: tmrl.core.builtins:JsonlRunLogger}}
  checkpoint_codec: {{class_path: {package}.components:TorchCheckpointCodec}}
training:
  total_transitions: 64
  max_episode_steps: 16
  batch_size: 8
  n_step: 1
  gamma: 0.99
  warmup_transitions: 8
  updates_per_transition: 1.0
  checkpoint_interval_updates: 16
"""


COMPONENTS = '''"""Editable components. Run `tmrl validate run.yaml` after each change."""

from pathlib import Path
from typing import Any, Mapping

import torch
from torch import nn

from tmrl.core.data import SampleBatch, Transition


class StarterFeaturePipeline:
    """Keep observations as PyTrees; replace this with TrackMania feature extraction."""

    def transform_observation(self, observation: Any) -> Any:
        return observation

    def collate(self, transitions: list[Transition]) -> dict[str, Any]:
        return {
            "observations": [item.observation for item in transitions],
            "actions": [item.action for item in transitions],
            "rewards": [item.reward for item in transitions],
            "next_observations": [item.next_observation for item in transitions],
            "terminated": [item.terminated for item in transitions],
            "truncated": [item.truncated for item in transitions],
        }


class StarterEnvironment:
    """Deterministic stand-in for a real TrackMania adapter during local checks."""

    def __init__(self, seed: int) -> None:
        self.seed = seed
        self.step_index = 0

    def reset(self, *, seed: int | None = None) -> tuple[dict[str, float], dict[str, Any]]:
        self.seed = self.seed if seed is None else seed
        self.step_index = 0
        return {"speed": 0.0}, {}

    def step(self, action: float) -> tuple[dict[str, float], float, bool, bool, dict[str, Any]]:
        self.step_index += 1
        speed = float(self.step_index)
        return {"speed": speed}, 1.0 - abs(float(action)), self.step_index >= 8, False, {}


class StarterEnvironmentFactory:
    """Replace with a factory that opens your local TrackMania adapter."""

    def create(self, *, seed: int) -> StarterEnvironment:
        return StarterEnvironment(seed)


class StarterMlpPolicy:
    """A small MLP policy; replace the scalar input with your real feature vector."""

    def __init__(self, network: nn.Module) -> None:
        self.network = network

    def act(self, observation: Any, *, deterministic: bool = False) -> float:
        del deterministic
        speed = float(observation.get("speed", 0.0))
        with torch.no_grad():
            return float(torch.tanh(self.network(torch.tensor([[speed]])).squeeze()).item())


class StarterMlpLearner:
    """Trainable contract example, not a complete racing algorithm."""

    def __init__(self) -> None:
        self.network = nn.Sequential(nn.Linear(1, 32), nn.ReLU(), nn.Linear(32, 1))
        self.optimizer = torch.optim.Adam(self.network.parameters(), lr=1e-3)
        self._policy = StarterMlpPolicy(self.network)

    def setup(self, context: Mapping[str, Any]) -> None:
        torch.manual_seed(int(context["seed"]))

    def update(self, batch: SampleBatch) -> Mapping[str, float]:
        speeds = torch.tensor(
            [[float(item.get("speed", 0.0))] for item in batch.data["observations"]]
        )
        targets = torch.tensor([[float(value)] for value in batch.data["rewards"]])
        loss = (self.network(speeds) - targets).square().mean()
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        return {"loss/starter": float(loss.item())}

    def policy(self) -> StarterMlpPolicy:
        return self._policy

    def state_dict(self) -> Mapping[str, Any]:
        return {"model": self.network.state_dict(), "optimizer": self.optimizer.state_dict()}

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        self.network.load_state_dict(state["model"])
        self.optimizer.load_state_dict(state["optimizer"])


class TorchCheckpointCodec:
    def save(self, state: Mapping[str, Any], path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(dict(state), path)

    def load(self, path: Path) -> Mapping[str, Any]:
        return torch.load(path, map_location="cpu", weights_only=False)
'''


def create_project(directory: str | Path, package: str, *, template: str = "starter") -> Path:
    """Create an installable, editable project without overwriting user files."""

    target = Path(directory)
    package_dir = target / "src" / package
    if target.exists() and any(target.iterdir()):
        raise FileExistsError(f"Refusing to overwrite non-empty directory {target}")
    package_dir.mkdir(parents=True, exist_ok=True)
    (target / "pyproject.toml").write_text(_pyproject(package.replace("_", "-")), encoding="utf-8")
    if template not in {"starter", "trackmania"}:
        raise ValueError("template must be 'starter' or 'trackmania'")
    config = _config(package) if template == "starter" else _trackmania_config()
    (target / "run.yaml").write_text(config, encoding="utf-8")
    if template == "trackmania":
        assets = target / "assets"
        assets.mkdir()
        (assets / "trajectory.csv").write_text("0,0,0\n1,0,0\n2,0,0\n", encoding="utf-8")
        import numpy as np

        boundary = np.asarray([[0, 0, -5], [5, 0, -5], [10, 0, -5]], dtype=np.float32)
        np.savez_compressed(
            assets / "test-3.geometry.npz",
            version=np.asarray("1"),
            map_uid=np.asarray("REPLACE_WITH_TEST_3_UID"),
            map_sha256=np.asarray(""),
            left=boundary,
            center=boundary + np.asarray([0, 0, 5], dtype=np.float32),
            right=boundary + np.asarray([0, 0, 10], dtype=np.float32),
            spacing_m=np.asarray(5.0, dtype=np.float32),
        )
        plugin_dir = target / "openplanet"
        plugin_dir.mkdir()
        plugin = files("tmrl.project").joinpath("openplanet/TMRL_GrabData_IQN.as")
        (plugin_dir / "TMRL_GrabData_IQN.as").write_text(
            plugin.read_text(encoding="utf-8"), encoding="utf-8"
        )
        (plugin_dir / "README.md").write_text(
            "Copy TMRL_GrabData_IQN.as to OpenplanetNext/Scripts, reload OpenPlanet, and "
            "manually load maps/test-3.Map.Gbx before tmrl smoke or tmrl benchmark.\n",
            encoding="utf-8",
        )
    (target / "run.py").write_text(
        "from tmrl import RunSpec, Trainer, resolve_run\n\n"
        "spec = RunSpec.from_yaml('run.yaml')\n"
        "run = resolve_run(spec)\n"
        "try:\n    Trainer(run).train()\nfinally:\n    run.logger.close()\n",
        encoding="utf-8",
    )
    (package_dir / "__init__.py").write_text("", encoding="utf-8")
    (package_dir / "components.py").write_text(COMPONENTS, encoding="utf-8")
    tests_dir = target / "tests"
    tests_dir.mkdir()
    (tests_dir / "test_components.py").write_text(
        f"from {package}.components import StarterMlpLearner\n\n\n"
        "def test_policy_is_constructible():\n"
        "    assert StarterMlpLearner().policy() is not None\n",
        encoding="utf-8",
    )
    return target


def _trackmania_config() -> str:
    return """api_version: \"1.1\"
run_id: trackmania-iqn-lidar
seed: 0
artifacts_dir: artifacts
components:
  learner:
    class_path: tmrl.algorithms.implicit_quantile_q_learning:ImplicitQuantileQLearning
    kwargs:
      learning_rate: 3.0e-5
      gradient_clip_norm: 1.0
      exploration_epsilon: 1.0
      exploration_epsilon_final: 0.05
      exploration_epsilon_decay_updates: 100000
  environment:
    class_path: tmrl.trackmania.environment:OpenPlanetEnvironmentFactory
    kwargs:
      config:
        trajectory_path: assets/trajectory.csv
        geometry_path: assets/test-3.geometry.npz
        expected_map_uid: REPLACE_WITH_TEST_3_UID
  model_factory:
    class_path: tmrl.trackmania.iqn:LidarIqnModelFactory
  replay_store:
    class_path: tmrl.core.replay:InMemoryReplayStore
  sampler:
    class_path: tmrl.core.replay:PrioritizedSampler
  feature_pipeline:
    class_path: tmrl.trackmania.features:LidarFeaturePipeline
    kwargs:
      geometry_path: assets/test-3.geometry.npz
      expected_map_uid: REPLACE_WITH_TEST_3_UID
  evaluator:
    class_path: tmrl.trackmania.evaluation:TrackmaniaEvaluator
  evaluation:
  name: test-3
  version: "1"
  maps:
    - id: test-3
      map_path: maps/test-3.Map.Gbx
      geometry_path: assets/test-3.geometry.npz
      expected_map_uid: REPLACE_WITH_TEST_3_UID
  trials_per_map: 20
training:
  total_transitions: 100000
  batch_size: 256
  n_step: 7
  gamma: 0.995
  warmup_transitions: 10000
"""
